import os
import asyncio
import aiohttp
from io import BytesIO
from PIL import Image, ImageDraw, ImageFont

from pyrogram import filters
from pyrogram.types import (
    Message, 
    InlineQuery, 
    InlineQueryResultPhoto, 
    InputTextMessageContent
)
from pyrogram.enums import ParseMode

from VipMusic import app
from VipMusic.core.mongo import mongodb

# --- DATABASE SETUP ---
upidb = mongodb.upi_db

async def get_upi(user_id: int):
    """Fetches the user's saved UPI ID."""
    data = await upidb.find_one({"user_id": user_id})
    return data["upi_id"] if data else None

async def save_upi(user_id: int, upi_id: str):
    """Saves or updates the user's UPI ID."""
    await upidb.update_one(
        {"user_id": user_id}, 
        {"$set": {"upi_id": upi_id}}, 
        upsert=True
    )

async def delete_upi(user_id: int):
    """Deletes the user's saved UPI ID."""
    await upidb.delete_one({"user_id": user_id})


# --- IMAGE PROCESSING ---
def generate_qr_poster(qr_bytes: bytes, amount: str, upi_id: str) -> BytesIO:
    """Composites the raw QR code onto a custom poster background."""
    qr_img = Image.open(BytesIO(qr_bytes)).convert("RGB")
    qr_img = qr_img.resize((400, 400), Image.Resampling.LANCZOS)
    
    base = Image.new("RGB", (600, 800), "white")
    draw = ImageDraw.Draw(base)
    
    try:
        font_bold = ImageFont.truetype("VipMusic/assets/font.ttf", 26)
        font_regular = ImageFont.truetype("VipMusic/assets/font2.ttf", 22)
        font_small = ImageFont.truetype("VipMusic/assets/font3.ttf", 18)
    except IOError:
        font_bold = ImageFont.load_default()
        font_regular = ImageFont.load_default()
        font_small = ImageFont.load_default()

    top_text_1 = f"Payment of ₹{amount}"
    top_text_2 = f"to {upi_id}"
    
    w1 = draw.textlength(top_text_1, font=font_bold)
    w2 = draw.textlength(top_text_2, font=font_regular)
    
    draw.text(((600 - w1) / 2, 80), top_text_1, fill="black", font=font_bold)
    draw.text(((600 - w2) / 2, 120), top_text_2, fill="dimgray", font=font_regular)

    border_box = [90, 190, 510, 610]
    draw.rectangle(border_box, outline="#4285F4", width=12)
    base.paste(qr_img, (100, 200))

    bottom_text_1 = "Scan to pay with any UPI app"
    bottom_text_2 = f"Generated by @{app.username}"
    
    w3 = draw.textlength(bottom_text_1, font=font_regular)
    w4 = draw.textlength(bottom_text_2, font=font_small)
    
    draw.text(((600 - w3) / 2, 670), bottom_text_1, fill="black", font=font_regular)
    draw.text(((600 - w4) / 2, 715), bottom_text_2, fill="darkgray", font=font_small)

    final_image = BytesIO()
    final_image.name = "UPI_QR.jpg"
    base.save(final_image, format="JPEG", quality=95)
    final_image.seek(0)
    
    return final_image


# --- CHAT COMMANDS ---

@app.on_message(filters.command("setupi"))
async def set_upi_cmd(_, message: Message):
    if len(message.command) < 2:
        return await message.reply_text(
            "**⚠️ Invalid Usage!**\n"
            "> **Example:** `/setupi your123@fam`",
            parse_mode=ParseMode.MARKDOWN
        )
    
    upi_id = message.text.split(None, 1)[1].strip()
    await save_upi(message.from_user.id, upi_id)
    await message.reply_text(
        f"**✅ UPI ID Successfully Saved!**\n> **Linked UPI:** `{upi_id}`",
        parse_mode=ParseMode.MARKDOWN
    )


@app.on_message(filters.command("delupi"))
async def del_upi_cmd(_, message: Message):
    await delete_upi(message.from_user.id)
    await message.reply_text(
        "**🗑️ UPI ID Successfully Deleted from database.**",
        parse_mode=ParseMode.MARKDOWN
    )


@app.on_message(filters.command("viewupi"))
async def view_upi_cmd(_, message: Message):
    upi_id = await get_upi(message.from_user.id)
    if not upi_id:
        return await message.reply_text(
            "**❌ No UPI ID Found!**\n"
            "> Use `/setupi [your_upi_id]` to link one.",
            parse_mode=ParseMode.MARKDOWN
        )
    
    await message.reply_text(
        f"**💳 Your Saved UPI ID:**\n> `{upi_id}`",
        parse_mode=ParseMode.MARKDOWN
    )


@app.on_message(filters.command("gen"))
async def gen_qr_cmd(_, message: Message):
    amount = None
    
    # Check if the user typed the amount directly (e.g., /gen 100)
    if len(message.command) > 1:
        amount = message.command[1].strip()
    # Or, check if the user replied to a message containing the amount
    elif message.reply_to_message and message.reply_to_message.text:
        amount = message.reply_to_message.text.strip()
        
    if not amount or not amount.isdigit():
        return await message.reply_text(
            "**⚠️ Invalid Usage!**\n"
            "> **Example:** `/gen 100` or reply to a valid amount with `/gen`",
            parse_mode=ParseMode.MARKDOWN
        )
    
    upi_id = await get_upi(message.from_user.id)
    if not upi_id:
        return await message.reply_text(
            "**❌ You haven't linked a UPI ID yet!**\n"
            "> Set it up first using: `/setupi [your_upi_id]`",
            parse_mode=ParseMode.MARKDOWN
        )

    api_url = f"https://subdict.qzz.io/genqr/?upi={upi_id}&amount={amount}&name=drxqr&img=1"

    # Send waiting message
    waiting_msg = await message.reply_text(
        "⭐ **Generating QR code, please wait...**",
        parse_mode=ParseMode.MARKDOWN
    )

    try:
        async with aiohttp.ClientSession() as session:
            async with session.get(api_url) as response:
                if response.status != 200:
                    await waiting_msg.delete()
                    return await message.reply_text(
                        "**❌ Failed to generate QR Code.**",
                        parse_mode=ParseMode.MARKDOWN
                    )
                qr_bytes = await response.read()

        loop = asyncio.get_event_loop()
        final_image = await loop.run_in_executor(None, generate_qr_poster, qr_bytes, amount, upi_id)

        caption = (
            f"**⭐ Payment of ₹{amount} to {upi_id}**\n\n"
            f"> **Scan to pay with any UPI app**\n"
            f"> **Generated by @{app.username}**\n\n"
            f"⭐ *This QR will expire in 10 minutes.*"
        )

        sent_message = await message.reply_photo(
            photo=final_image,
            caption=caption,
            parse_mode=ParseMode.MARKDOWN
        )
        
        await waiting_msg.delete()
        
        # Wait for 10 minutes (600 seconds)
        await asyncio.sleep(600)
        
        try:
            await sent_message.delete()
            await message.reply_text("**❌ QR Expired**", quote=True, parse_mode=ParseMode.MARKDOWN)
        except Exception:
            try:
                await app.send_message(message.chat.id, "**❌ QR Expired**", parse_mode=ParseMode.MARKDOWN)
            except:
                pass

    except Exception as e:
        await waiting_msg.delete()
        await message.reply_text(
            f"**❌ An error occurred:**\n> `{str(e)}`",
            parse_mode=ParseMode.MARKDOWN
        )


# --- INLINE MODE ---

@app.on_inline_query()
async def inline_qr_handler(_, inline_query: InlineQuery):
    text = inline_query.query.strip()
    
    if not text.lower().startswith("gen"):
        return

    parts = text.split(None, 1)
    if len(parts) < 2:
        await inline_query.answer(
            results=[],
            switch_pm_text="Usage: gen [amount]",
            switch_pm_parameter="inline_qr_usage"
        )
        return

    amount = parts[1].strip()
    if not amount.isdigit():
        return

    user_id = inline_query.from_user.id
    upi_id = await get_upi(user_id)
    
    if not upi_id:
        await inline_query.answer(
            results=[],
            switch_pm_text="❌ Setup your UPI ID first!",
            switch_pm_parameter="setupi"
        )
        return

    api_url = f"https://subdict.qzz.io/genqr/?upi={upi_id}&amount={amount}&name=drxqr&img=1"

    caption = (
        f"**Payment of ₹{amount} to {upi_id}**\n\n"
        f"> **Scan to pay with any UPI app**\n"
        f"> **Generated by @{app.username}**"
    )

    results = [
        InlineQueryResultPhoto(
            id=f"qr_{amount}_{user_id}",
            photo_url=api_url,
            thumb_url=api_url,
            title=f"Generate QR for ₹{amount}",
            description=f"Send a QR poster to pay {upi_id}",
            caption=caption,
            parse_mode=ParseMode.MARKDOWN
        )
    ]

    await inline_query.answer(results, cache_time=0)